---
  - hosts: all
    gather_facts: yes
    tasks:
      - name: check if reboot is required
        win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - DefinitionUpdates
            - UpdateRollups
            - Updates
            - ServicePacks
          log_path: C:\ansible_wu.txt
        register: update_result

      - name: pre-update reboot
        win_reboot:
          msg: "Reboot required before updates can be installed."
          reboot_timeout: 6000
        when: update_result.reboot_required or ansible_reboot_pending