---
- name: Atualizacao do Windows
  hosts: all 

  tasks:

  - name: Install all security updates with automatic reboots
    ansible.windows.win_updates:
      category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - DefinitionUpdates
          - Updates
      reboot: yes
      log_path: C:\ansible_wu.txt